### ISSUE TITLE
error when running on phantomjs

### ISSUE THREAD

**Issue by hankpillow** [rafaelrinaldi/unicorn#4] opened 2014-02-17 17:00 UTC
Hi rafael, great lib dude.

I'm trying to use it inside a phatomjs script and I'm seeing this statck error:

``` bash
Error: Cannot find module 'util'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
 .../bin/rquery/node_modules/unicorn/lib/unicorn.js:30
.../bin/rquery/node_modules/unicorn/lib/unicorn.js:125
TypeError: 'undefined' is not a function (evaluating 'require("unicorn").install()')
```

**Comment by nickdesaulniers** [comment] 2014-04-29 06:47
I'm seeing this error as well, but with other libs.  Looks like a phantomjs issue?

**Comment by rafaelrinaldi** [comment] 2015-01-13 22:26
@nickdesaulniers Yeah, PhantomJS is based on a shitty WebKit version who doesn't even support `Function.bind`. I'm working on this.

**Comment by rafaelrinaldi** [comment] 2015-11-18 13:43
@hankpillow @nickdesaulniers The problem is that PhantomJS doesn't share Node's stdlib. `unicorn` relies on `util/format` to do the string substitution for the ANSI characters.

I strongly suggest you to move to [`chalk`](https://github.com/chalk/chalk) which has a very stable API, don't mess with native object and is today what I wanted `unicorn` to be when I first wrote it.

Thanks for the discussion, gentlemen but I'm no longer maintaining this project. [Let me know](https://github.com/rafaelrinaldi/contact) if you want to take ownership over it.

I'm closing this issue.

**Closed as completed by rafaelrinaldi** 2015-11-18 13:43 UTC
Labels: bug
